- README.md
- lib/bibliothecary/analyser.rb
- lib/bibliothecary/parsers/pypi.rb
- spec/bibliothecary_spec.rb
- spec/fixtures/Pipfile
- spec/fixtures/Pipfile.lock
- spec/parsers/pypi_spec.rb
> Add support for Pipfile and Pipefile.lock

- lib/bibliothecary/parsers/haxelib.rb
- spec/bibliothecary_spec.rb
- spec/fixtures/haxelib.json
- spec/parsers/haxelib_spec.rb
One improvement towards https://github.com/librariesio/supporters/issues/7
> Add support for haxelib.json, fixes #341

- lib/bibliothecary/analyser.rb
- lib/bibliothecary/parsers/bower.rb
- lib/bibliothecary/parsers/cpan.rb
- lib/bibliothecary/parsers/dub.rb
- lib/bibliothecary/parsers/elm.rb
- lib/bibliothecary/parsers/haxelib.rb
- lib/bibliothecary/parsers/meteor.rb
- lib/bibliothecary/parsers/npm.rb
- lib/bibliothecary/parsers/nuget.rb
- lib/bibliothecary/parsers/packagist.rb
- lib/bibliothecary/parsers/pub.rb
Deletes about 100 lines of boilerplate from a number of parsers :feelsgood:
> Refactor out some duplicate methods into the Analyser module

- lib/bibliothecary.rb
- spec/bibliothecary_spec.rb
Fixes https://github.com/librariesio/bibliothecary/issues/371
If so then please replace this section with a link to the ticket(s) it addressed, an explanation of your change and why you think we should include it. Thanks again!
> Ingnore vendor/ directory

- bibliothecary.gemspec
- bin/bibliothecary
- lib/bibliothecary/cli.rb
Just one command for now, but using [commander](https://github.com/commander-rb/commander) so it's easy to add more later:
```
$ bibliothecary list --path path/to/my/repository
```
> CLI interface for listing dependencies in a given path

- lib/bibliothecary/analyser.rb
- lib/bibliothecary/parsers/bower.rb
- lib/bibliothecary/parsers/cargo.rb
- lib/bibliothecary/parsers/carthage.rb
- lib/bibliothecary/parsers/clojars.rb
- lib/bibliothecary/parsers/cocoapods.rb
- lib/bibliothecary/parsers/cpan.rb
- lib/bibliothecary/parsers/cran.rb
- lib/bibliothecary/parsers/dub.rb
- lib/bibliothecary/parsers/elm.rb
- lib/bibliothecary/parsers/go.rb
- lib/bibliothecary/parsers/hackage.rb
- lib/bibliothecary/parsers/haxelib.rb
- lib/bibliothecary/parsers/hex.rb
- lib/bibliothecary/parsers/julia.rb
- lib/bibliothecary/parsers/maven.rb
- lib/bibliothecary/parsers/meteor.rb
- lib/bibliothecary/parsers/npm.rb
- lib/bibliothecary/parsers/nuget.rb
- lib/bibliothecary/parsers/packagist.rb
- lib/bibliothecary/parsers/pub.rb
- lib/bibliothecary/parsers/pypi.rb
- lib/bibliothecary/parsers/rubygems.rb
- lib/bibliothecary/parsers/shard.rb
- lib/bibliothecary/parsers/swift_pm.rb
- spec/parsers/bower_spec.rb
- spec/parsers/elm_spec.rb
- spec/parsers/npm_spec.rb
- spec/parsers/pypi_spec.rb
Thanks taking the time to contribute. This template should help guide you through the process of creating a pull request for review. Please erase any part of this template that is not relevant to your pull request:
> Enable mono repo support by tweaking regexes to allow sub directories

- lib/bibliothecary/analyser.rb
- lib/bibliothecary/parsers/maven.rb
Thanks taking the time to contribute. This template should help guide you through the process of creating a pull request for review. Please erase any part of this template that is not relevant to your pull request:
If so then please replace this section with a link to the ticket(s) it addressed, an explanation of your change and why you think we should include it. Thanks again!
> Rescue Exception because C bindings throw Exceptions not StandardError

- .tidelift.yml
Thanks taking the time to contribute. This template should help guide you through the process of creating a pull request for review. Please erase any part of this template that is not relevant to your pull request:
If so then please replace this section with a link to the ticket(s) it addressed, an explanation of your change and why you think we should include it. Thanks again!
> Add .tidelift.yml file to ignore test directory for manifests

- lib/bibliothecary/parsers/npm.rb
- spec/fixtures/2018-package-lock/package-lock.json
- spec/parsers/npm_spec.rb
We were marking all package-lock.json deps as runtime, fix that.
> Convert "dev":true in package-lock.json to type="development"

- .rubocop.yml
- lib/bibliothecary/analyser.rb
- lib/bibliothecary/parsers/go.rb
- lib/bibliothecary/parsers/hackage.rb
- lib/bibliothecary/parsers/maven.rb
- lib/sdl_parser.rb
- spec/parsers/maven_spec.rb
- spec/parsers/npm_spec.rb
* updates Rubocop rules
* runs `rubocop -a` to autofix rule violations
> Update rubocop yaml

- lib/bibliothecary/parsers/maven.rb
- spec/fixtures/pom.xml
- spec/parsers/go_spec.rb
- spec/parsers/maven_spec.rb
- spec/parsers/rubygems_spec.rb
This will resolve properties that are hanging out inside of a string like `http://www.myhomepage.com/${project.artifactId}`. It will also recurse up to 5 times to resolve a property. Added some changes to the spec pom file to verify the resolved values.
> More Maven Property Resolving

- lib/bibliothecary/parsers/maven.rb
- spec/fixtures/pom.xml
- spec/parsers/maven_spec.rb
See https://search.maven.org/artifact/com.fasterxml.jackson.jaxrs/jackson-jaxrs-cbor-provider/2.10.0.pr1/bundle
```xml
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
<modelVersion>4.0.0</modelVersion> 
<parent>
<groupId>com.fasterxml.jackson.jaxrs</groupId>
<artifactId>jackson-jaxrs-providers</artifactId>
<version>2.10.0.pr1</version>
</parent>
...
<dependencies>
<dependency>
<artifactId>jackson-jaxrs-base</artifactId>
<groupId>${project.groupId}</groupId>
<version>${project.version}</version>
</dependency>
```
> Pull values from <parent>

- .travis.yml
From https://docs.travis-ci.com/user/languages/ruby/#dependency-management
> Use bundler <2

- lib/bibliothecary/analyser.rb
- lib/bibliothecary/parsers/conda.rb
- spec/parsers/conda_spec.rb
- spec/vcr/Bibliothecary_Parsers_Conda/parses_dependencies_from_environment_yml.yml
This makes Conda override analyse_contents_from_info  so it can return more than one analysis.
> Allow multiple kinded analyses

- lib/bibliothecary/parsers/conda.rb
- lib/bibliothecary/related_files_info.rb
- lib/bibliothecary/runner.rb
- spec/bibliothecary_spec.rb
> Allow matching from multiple kinds

- lib/bibliothecary/parsers/maven.rb
- spec/fixtures/sbt-update-full.txt
- spec/parsers/maven_spec.rb
Parsing freeform text output with regexes, breakfast of champions
> Add a parser for output of `sbt 'show updateFull'`

- lib/bibliothecary/parsers/pypi.rb
- spec/fixtures/poetry.lock
- spec/fixtures/pyproject.toml
- spec/parsers/pypi_spec.rb
should we leave pyproject.toml versions as `^3.0.6` or change that to `>3.0.6` style?
> Initial pass at parsing Poetry

- lib/bibliothecary/parsers/maven.rb
- lib/bibliothecary/version.rb
- spec/parsers/maven_spec.rb
- spec/vcr/Bibliothecary_Parsers_Maven/gradle/cleans_up_incorrectly_parsed_dependencies.yml
- spec/vcr/Bibliothecary_Parsers_Maven/gradle/parses_dependencies_from_build_gradle.yml
- spec/vcr/Bibliothecary_Parsers_Maven/gradle/removes_comments.yml
Seems that the gradle parsing service does a poor job when there's no version requested.
> Handle ungood build.gradle parsing results better

- .circleci/config.yml
- lib/bibliothecary/version.rb
- spec/parsers/npm_spec.rb
I realized a spec from my last PR was broken and it wasn't failing checks. This adds the CircleCI config so we can turn that check on, and it also fixes my broken spec 🌞
> Add CircleCI config

- README.md
- lib/bibliothecary/parsers/nuget.rb
- spec/fixtures/nuget_project.assets.json
- spec/parsers/nuget_spec.rb
Allow parsing the nuget `project.assets.json` files.
> parse nuget assets files

- lib/bibliothecary.rb
- lib/bibliothecary/analyser.rb
- lib/bibliothecary/runner.rb
- lib/bibliothecary/version.rb
- spec/bibliothecary_spec.rb
Allow users of Bibliothecary to use alternate spelling of these API methods.
> Alias analyse methods to analyze

- lib/bibliothecary/parsers/maven.rb
- lib/bibliothecary/version.rb
- spec/fixtures/pom.xml
- spec/parsers/maven_spec.rb
Fixes https://app.bugsnag.com/tidelift/libraries-dot-io/errors/607ef348c9383d0007e18b41
> Maven: allow for CDATA fields while parsing pom

- lib/bibliothecary/parsers/packagist.rb
- spec/parsers/packagist_spec.rb
After some thought I got this wrong in my last PR: 
Instead of `{requirement: "1.0.0", drupal_requirement: "8.x-1.0"}`, let's return `{original_requirement: "1.0.0", requirement: "8.x-1.0"}`
> Drupal: swap the two requirement values returned from lockfile.

- lib/bibliothecary/parsers/nuget.rb
> Remove extra line added during merge conflict fix

- CHANGELOG.md
- lib/bibliothecary/version.rb
bump version and add changelog notes
> make changelog updates for yarn v4 publish

- lib/bibliothecary/multi_parsers/spdx.rb
- lib/bibliothecary/version.rb
Fixes a regression introduced in #603
> Fix purl platforms

- .tidelift
- .tidelift.yml
> Move the single parameter from .tidelift.yml to .tidelift

- lib/bibliothecary/parsers/pypi.rb
- lib/bibliothecary/version.rb
- spec/fixtures/Pipfile
- spec/fixtures/Pipfile.lock
- spec/parsers/pypi_spec.rb
* `path` parameter: https://pipenv-searchable.readthedocs.io/basics.html#editable-dependencies-e-g-e
* `file` parameter: there are no explicit docs about this, but [everything I see points to it being used for local flies](https://github.com/pypa/pipfile?tab=readme-ov-file#pipfile)
> Pipfile and Pipfile.lock: detect and set "local: true" on local deps

- CHANGELOG.md
- lib/bibliothecary/parsers/npm.rb
- spec/fixtures/package.json
- spec/fixtures/pnpm-lockfile-version-5/package.json
- spec/fixtures/pnpm-lockfile-version-5/pnpm-lock.yaml
- spec/fixtures/pnpm-lockfile-version-6/package.json
- spec/fixtures/pnpm-lockfile-version-6/pnpm-lock.yaml
- spec/fixtures/pnpm-lockfile-version-9/package.json
- spec/fixtures/pnpm-lockfile-version-9/pnpm-lock.yaml
- spec/parsers/npm_spec.rb
* refactor PNPM code into separate version-specific methods
* adds alias support for PNPM
* cut 12.1.5
> 12.1.15: adds PNPM alias support

- CHANGELOG.md
- lib/bibliothecary/parsers/nuget.rb
- lib/bibliothecary/version.rb
- spec/fixtures/example-references-tag.csproj
- spec/parsers/nuget_spec.rb
e.g.:
``` xml
<ItemGroup>
<Reference Include="Newtonsoft.Json, Version=13.0.3, Culture=neutral, PublicKeyToken=abcd1234abcd1234, processorArchitecture=MSIL" />
...
<ItemGroup>
```
> 12.3.0: Nuget: add support for <Reference> deps in *.csproj manifests

- CHANGELOG.md
- lib/bibliothecary/parsers/pypi.rb
- lib/bibliothecary/version.rb
- spec/bibliothecary_spec.rb
- spec/parsers/pypi_spec.rb
This leads to some downstream test weirdness.
> Don't parse conda files in the pypi parser
