lib/bibliothecary/parsers/pypi.rb
spec/parsers/pypi_spec.rb

I wanted to add support for requirements files in the following format: `*-requirements.txt`.
It turns out this format is already support since the regular expression match function checks for match anywhere in the string and doesn't require input string to start with `require` (aka `^require`).
If nothing else, the tests should at least still be useful :)

Python requirements file detection improvements

---

lib/bibliothecary/parsers/nuget.rb
spec/bibliothecary_spec.rb
spec/fixtures/paket.lock
spec/parsers/nuget_spec.rb

[Paket](http://fsprojects.github.io/Paket/) is an alternative Nuget client for the .net ecosystem that also handle git and file-based dependencies.  This PR teaches the Nuget parser how to read the [lockfiles](http://fsprojects.github.io/Paket/lock-file.html) generated by paket, which contain every dependency across the entire solution.
I'm not sure how detailed the dependency descriptions are, but this just handles the most common use case for paket: Nuget dependencies.  If there is enough demand I could expand the parser to learn about git, github, file, and group dependencies.

teach the nuget parser how to handle paket lockfiles

---

lib/bibliothecary/parsers/go.rb
spec/fixtures/gb_manifest
spec/parsers/go_spec.rb

Added gb manifest parsing to the `go.rb` parser, and associated tests.

Adding manifest parser for gb (Golang vendoring tool)

---

lib/bibliothecary/parsers/nuget.rb
spec/fixtures/example.csproj
spec/parsers/nuget_spec.rb

.NET Core 1 Preview used project.json, the final version uses .csproj in xml format. The actual parsing is pretty much like the packages.conf files for .NET Framework projects so the functionality is mostly reused. Tests added and passes.

Added support for csproj

---

spec/bibliothecary_spec.rb

This test was depending on the state of the repo pretty heavily
and needed to be updated whenever deps were updated. There's already
a good framework for testing specific parsers against fixtures so
we don't need to do that in this test also.

Make test less fragile

---

lib/bibliothecary/parsers/pypi.rb
spec/fixtures/requirements.txt
spec/fixtures/setup.py
spec/parsers/pypi_spec.rb

python packages can be versioned something like 2.0beta1. This
fixes bibliothecary to allow that type of version
Fixes https://github.com/librariesio/libraries.io/issues/1829

Allow requirements like 2.0beta1 for python packages

---

README.md
lib/bibliothecary.rb
lib/bibliothecary/configuration.rb
lib/bibliothecary/parsers/carthage.rb
lib/bibliothecary/parsers/clojars.rb
lib/bibliothecary/parsers/hex.rb
lib/bibliothecary/parsers/maven.rb
lib/bibliothecary/parsers/npm.rb
lib/bibliothecary/parsers/swift_pm.rb
spec/bibliothecary_spec.rb
spec/configuration_spec.rb
spec/spec_helper.rb

This will make using bibliothecary inside of docker, behind a firewall or just without depending on Libraries.io infrastructure much easier to do. 
Fixes https://github.com/librariesio/bibliothecary/issues/160
Example:
```ruby
Bibliothecary.configure do |config|
config.mix_parser_host = 'http://my-mix-parser-web-service.com'
end
```
Still needs:

Allow configuration of parser urls and ignored files at runtime

---

lib/bibliothecary/analyser.rb
lib/bibliothecary/parsers/maven.rb
spec/fixtures/ivy_reports/com.example-hello_2.12-compile.xml
spec/fixtures/ivy_reports/com.example-hello_2.12-test.xml
spec/fixtures/ivy_reports/com.example-subproject_2.12-compile.xml
spec/fixtures/ivy_reports/com.example-subproject_2.12-test.xml
spec/fixtures/ivy_reports/invalid_syntax.xml
spec/fixtures/ivy_reports/missing_info.xml
spec/fixtures/ivy_reports/non_ivy_report.xml
spec/parsers/maven_spec.rb
spec/spec_helper.rb

Yak shaves involved:
* allow parser mappings to have a content_matcher method to
look at the file contents
* optionally pass contents into the analyser methods to cut down
on how many times we re-load the file

Add support for parsing `<ivy-report>` XML documents

---

lib/bibliothecary.rb
lib/bibliothecary/analyser.rb
lib/bibliothecary/exceptions.rb
lib/bibliothecary/parsers/maven.rb
spec/fixtures/broken/pom.xml
spec/parsers/maven_spec.rb

This cleans up error handling to make a bit more sense and gets the message from any exception thrown into the returned analysis hash.

Report error text

---

lib/bibliothecary.rb
lib/bibliothecary/analyser.rb
lib/bibliothecary/file_info.rb
spec/bibliothecary_spec.rb
spec/fixtures/multimanifest_dir/com.example-hello_2.12-compile.xml
spec/parsers/maven_spec.rb

What's happening here:
* in libraries.io, when scanning repositories, we get a bunch of relative path names from GitHub, filter those by regex, and then download only some of them to analyze the contents
* but in Bibliothecary.analyse, we have an actual local directory which means
- we can look at the file contents
- to look at the file contents we need an open-able path name which can be relative to pwd but NOT relative to the project directory which may not be pwd
In this PR I'm creating a FileInfo object which has "what we know about a file" and lazy-loads the contents the first time we try to look at them. The project folder path can be nil and the contents can be nil, for the "we just have relative paths from GitHub" case.
FileInfo has three purposes
* lazy-load contents
* avoid …

Adjust how we handle absolute/relative paths and file contents

---

lib/bibliothecary/parsers/maven.rb

Use locate() instead. Not sure why/when root is missing,
but apparently it can be in production.
Also, catch any exceptions in ivy_report? matcher,
since we aren't going to handle them at that point.
This does mean we may have worse error messages
when a file doesn't have ivy-report at the root,
since we won't even get around to trying to parse it.
Future solution might be to have a mode where
all files are expected to be parseable (and we might
not even do the match first).

Avoid root method on result of 0x.parse_file_contents

---

lib/bibliothecary.rb
lib/bibliothecary/configuration.rb
spec/bibliothecary_spec.rb

* there's now an ignored_files configuration option
* ignored_dirs now matches entire relative path not only basename
* test for ignored_dirs actually works
* in identify_manifests, ignoring "foo" no longer ignores "foobar",
but still ignores "foo/bar"
ignored_dirs previously matched the dir anywhere that the basename
occurred in the hierarchy, and had to be a single filename not a path.
This was in the "we have a local checkout" case.
But when identifying manifests without a local checkout, it
required the dir to be at the start of the path.
It now consistently works the same way, you _can_ ignore `spec/fixtures`
but ignoring only `fixtures` won't match that. This isn't compatible
with one of the cases, but seems more expected overall?
ignored_dirs test had a test that always succeeded …

Add ignored_files and fixes to ignored_dirs

---

lib/bibliothecary/analyser.rb
lib/bibliothecary/parsers/bower.rb
lib/bibliothecary/parsers/cargo.rb
lib/bibliothecary/parsers/carthage.rb
lib/bibliothecary/parsers/clojars.rb
lib/bibliothecary/parsers/cocoapods.rb
lib/bibliothecary/parsers/cpan.rb
lib/bibliothecary/parsers/cran.rb
lib/bibliothecary/parsers/dub.rb
lib/bibliothecary/parsers/elm.rb
lib/bibliothecary/parsers/go.rb
lib/bibliothecary/parsers/hackage.rb
lib/bibliothecary/parsers/haxelib.rb
lib/bibliothecary/parsers/hex.rb
lib/bibliothecary/parsers/julia.rb
lib/bibliothecary/parsers/maven.rb
lib/bibliothecary/parsers/meteor.rb
lib/bibliothecary/parsers/npm.rb
lib/bibliothecary/parsers/nuget.rb
lib/bibliothecary/parsers/packagist.rb
lib/bibliothecary/parsers/pub.rb
lib/bibliothecary/parsers/pypi.rb
lib/bibliothecary/parsers/rubygems.rb
lib/bibliothecary/parsers/shard.rb
lib/bibliothecary/parsers/swift_pm.rb
lib/bibliothecary/version.rb

I'm able to get around a 5x speedup by ditching regexes for matching paths.
I've left the original regexes in place for comparison, I'll remove them before this merges.
The first commit fixes a spec that's failing on master (at least for me locally)

Don't use regexes while matching paths

---

lib/bibliothecary/parsers/maven.rb
spec/fixtures/pom.xml
spec/parsers/maven_spec.rb

This adds support for the `<dependencyManagement>` namespace tag in pom.xml, which can be used to define a parent pom.xml's deps/versions. Children then define these without a version, and inherit the versions from the parents.
Maven docs [here](https://maven.apache.org/pom.html#Dependency_Management). Addresses https://github.com/librariesio/bibliothecary/issues/74 .

Add support for <dependencyManagement> namespace in pom.xml

---

README.md
lib/bibliothecary/parsers/go.rb
spec/fixtures/go.mod
spec/fixtures/go.sum
spec/parsers/go_spec.rb

Kicking this off. 
* [Go Modules wiki](https://github.com/golang/go/wiki/Modules)
* [Go Modules proposal](https://go.googlesource.com/proposal/+/master/design/24301-versioned-go.md)
* [good intro to Go Modules](https://roberto.selbach.ca/intro-to-go-modules/)
* [go-yaml/yaml on GH](https://github.com/go-yaml/yaml)
* [go-yaml/yaml on go-search](https://go-search.org/view?id=gopkg.in%2fyaml.v2)
* [go-yaml/yaml on Libraries, notably missing deps](https://libraries.io/go/github.com%2Fgo-yaml%2Fyaml)

Adding parser support for Go Modules

---

lib/bibliothecary/parsers/rubygems.rb
lib/bibliothecary/version.rb
spec/fixtures/GemfileLineEndings.lock
spec/parsers/rubygems_spec.rb

We tried scanning a file that appears to have been made on windows. This caused there to be an error message of: `Gemfile.lock: undefined method 'gsub' for nil:NilClass"` because the match didn't match ` name (ver)\r`
Deciding to chomp away the newline characters

Rubygems parser Gemfile.lock chomp nonprinting newline chars

---

lib/bibliothecary/parsers/maven.rb
lib/bibliothecary/version.rb
spec/fixtures/pom.xml
spec/parsers/maven_spec.rb
spec/spec_helper.rb

The idea is that properties from parent pom files can be passed in and be used to resolve dependency values.

Allow Additional Properties to be Added to maven parse_pom_manifest

---

lib/bibliothecary/parsers/conda.rb
spec/fixtures/conda_with_pip/environment.yml
spec/parsers/conda_spec.rb
spec/vcr/Bibliothecary_Parsers_Conda/parses_dependencies_from_environment_yml_with_pip.yml

This checks for a `- pip:` entry in the yaml, and then parses that as "requirements.txt" data, returning an Analysis for that with the Condas data.
Not sure if this is the right approach, but it seems to work.

First pass on making Conda support Pip manifest

---

lib/bibliothecary/parsers/nuget.rb
spec/fixtures/packages.lock.json

Problem:
lockfile can have multiple frameworks.
Incidentally one we picked had the frameworks ordered that the `.last` was an empty one.
This PR deletes any empty frameworks from the frameworks hash, then returns the `.last` one of these with any values.
If there's none, continues on returning empty array.

Pick a different framework in nuget

---

lib/bibliothecary/parsers/maven.rb

Fixes https://app.bugsnag.com/tidelift/libraries-dot-io/errors/5ffcc76ae4560f0017add9ac

Only match pom dep for maven properties if the field is present.

---

lib/bibliothecary/parsers/nuget.rb
lib/bibliothecary/version.rb
spec/fixtures/example.csproj
spec/parsers/nuget_spec.rb

Sometimes Versions show up as nodes instead of attributes 🤷

Handle nested version nodes in package references

---

lib/bibliothecary.rb
lib/bibliothecary/parsers/conda.rb
lib/bibliothecary/parsers/pypi.rb
lib/bibliothecary/runner.rb
lib/bibliothecary/version.rb
spec/bibliothecary_spec.rb
spec/parsers/conda_spec.rb
spec/parsers/pypi_spec.rb
spec/vcr/Bibliothecary/handles_a_dual-platformed_file_pip/conda_.yml

Trying out a bit of a hybrid approach where we rely on conda-parser for the primary conda bits, and then added some of the previous code back for parsing pip-in-conda dependencies. I have to dig in a little more here, because I don't think Bibliothecary#analyse_file should be producing an array. 
I'm wondering if we should have the pypi parser do this and figure out some way to let both parsers have at the file.

Add pip parsing to conda environment yaml files

---

bibliothecary.gemspec
lib/bibliothecary.rb
lib/bibliothecary/parsers/cargo.rb
lib/bibliothecary/parsers/go.rb
lib/bibliothecary/parsers/pypi.rb
lib/bibliothecary/version.rb

Citrus/toml-rb was segfaulting on ruby 3.0. I saw an open issue but didn't dig super hard since we can just swap libraries and things work just fine. https://github.com/mjackson/citrus/issues/60

Update toml library for ruby 3 compatibility

---

lib/bibliothecary/parsers/maven.rb
lib/bibliothecary/version.rb
spec/fixtures/maven-dependency-tree.txt
spec/parsers/maven_spec.rb

When parsing a `maven-dependency-tree.txt`, the first dep will be the package you're parsing. This skips that first dep so it's not counted as a dep of itself.

maven-dependency-tree.txt: prevent package name from being listed as a dep.

---

lib/bibliothecary/parsers/maven.rb
lib/bibliothecary/version.rb
spec/fixtures/maven-dependency-tree.txt

When [removing the package itself from a maven dep tree](https://github.com/librariesio/bibliothecary/pull/505), we should treat  `GROUP:NAME:SOURCE:VERSION:TYPE` the same if `TYPE` differs.

parse_maven_tree: ignore package type when removing package from list

---

lib/bibliothecary/parsers/packagist.rb
lib/bibliothecary/version.rb
spec/fixtures/composer.json
spec/fixtures/composer.lock
spec/parsers/packagist_spec.rb

Drupal has a Composer repository at `https://packages.drupal.org/{7,8}`, and most Drupal packages in a Composer manifest will point to that (versus Packagist). 
However, Drupal's repository uses a mapper that translates the semver that Composer asks for into Drupal-compatible versions, e.g. `8-x.2-1` (this example translates to version `2.1.0` that is compatible with Drupal 8).
This change returns the Drupal version instead of the semver version if the package is a Drupal one.
```
...
{
"name": "drupal/allowed_formats",
"version": "1.3.0",
"source": {
"type": "git",
"url": "https://git.drupalcode.org/project/allowed_formats.git",
"reference": "8.x-1.3"
},
...
}
...
```
After this change, Bibliothecary would return `{name: "drupal/allowed_formats", requirement: "1.3.0", drupal_requirement: …

Add support for Drupal Composer repo by returning Drupal version.

---

lib/bibliothecary/parsers/pypi.rb
lib/bibliothecary/version.rb
spec/fixtures/pip-compile/requirements.in
spec/parsers/pypi_spec.rb

Thought I'd add in `.in` files too for `requirements.in` support as a manifest.

7.1.3 - Add *.in as matching manifest file

---

lib/bibliothecary/parsers/maven.rb
spec/fixtures/gradle-dependencies-q.txt
spec/parsers/maven_spec.rb

The first item here can't be parsed because there's no version, but the second version should be parsed as `1.1.0` instead of `1.1.0 FAILED`:
```
...
+--- org.projectlombok:lombok FAILED
\--- org.apiguardian:apiguardian-api:1.1.0 FAILED
...
```

Handle gradle-dependencies-q.txt lines ending in " FAILED"

---

lib/bibliothecary/parsers/npm.rb
lib/bibliothecary/related_files_info.rb
spec/parsers/npm_spec.rb

npm-shrinkwrap.json overrides other lockfiles when used with npm. Ensure that it's first, regardless of directory sort order.

Ensure npm-shrinkwrap takes precedence over other NPM lockfiles

---

lib/bibliothecary/analyser.rb
lib/bibliothecary/parsers/generic.rb
spec/bibliothecary_spec.rb
spec/fixtures/dependencies.csv
spec/parsers/generic_spec.rb

This allows directly putting data into the canonical bibliothecary form.
In this commit, a `dependencies.csv` can only contain a single platform,
due to the need to refactor the bibliothecary API before we can return
multiple platforms from a single file.

Support a `dependencies.csv` file format that's just uninterpreted

---

README.md
lib/bibliothecary/parsers/maven.rb
lib/bibliothecary/version.rb
spec/fixtures/build.gradle.kts
spec/fixtures/gradle_with_kotlin/gradle-dependencies-q.txt
spec/parsers/maven_spec.rb

* accept `build.gradle.kts` but return empty list of deps (the parser work is ongoing)
* adds a spec fixture for a `gradle-dependencies-q.txt` file generated from a `build.gradle.kts`, just to document the output
(Re-do of https://github.com/librariesio/bibliothecary/pull/526/)

[7.3.5] Pre-support for build.gradle.kts

---

lib/bibliothecary/parsers/generic.rb
lib/bibliothecary/version.rb
spec/parsers/generic_spec.rb

When a dependencies.csv has a blank field, we were check for emptiness without checking for nilness first:
```{:dependencies=>nil, :error_message=>"dependencies.csv: undefined method `empty?' for nil:NilClass", :kind=>"lockfile", :path=>"dependencies.csv", :platform=>"generic", :success=>false}```
```{:dependencies=>nil, :error_message=>"dependencies.csv: missing field 'requirement' on line 1", :kind=>"lockfile", :path=>"dependencies.csv", :platform=>"generic", :success=>false}```

Fix error for missing fields in dependencies.csv parser

---

lib/bibliothecary/parsers/maven.rb
lib/bibliothecary/version.rb
spec/fixtures/build.gradle.kts
spec/parsers/maven_spec.rb

* refactor the `build.gradle.kts` parsing regexes 
* add support for interpolated verisons, e.g. `group:artifactId:${someVar["my-version"]}`
* and start returning the method used for the dep in`type` , e.g. "implementation". This is what the `build.gradle` parser currently does as well
Folllowup to https://github.com/librariesio/bibliothecary/pull/532

[8.2.1] Expand simple parsing support for build.gradle.kts

---

lib/bibliothecary/parsers/pypi.rb
lib/bibliothecary/version.rb
spec/parsers/pypi_spec.rb

Sometimes these files are just non-dependency related configuration.

Gracefully handle pypoetry.toml files with no dependencies.

---

lib/bibliothecary/parsers/maven.rb
lib/bibliothecary/version.rb
spec/parsers/maven_spec.rb

* simplify the Groovy/Kotlin regexes: we don't need to parse the comments/closures/etc at the end of the lines
* this means we'll start picking up deps that open a closure on the same line, e.g. `implementation "foo:bar:1.2.3", { ...`
* also support Groovy deps that are wrapped in parens (like Kotlin), e.g. `implementation("foo:bar:1.2.3")`

Support more gradle syntax variations.

---

lib/bibliothecary/parsers/maven.rb
lib/bibliothecary/version.rb
spec/fixtures/gradle-dependencies-q.txt
spec/parsers/maven_spec.rb

Dependencies which resolve with a package rename are using the pre-rename name for a dependency
ThIs change resolves to the new name, instead of pre-rename

handle gradle deps which resolve with a rename

---

lib/bibliothecary/parsers/maven.rb
lib/bibliothecary/version.rb
spec/parsers/maven_spec.rb

When we see an alias in `gradle-dependencies-q.txt`, capture `:original_name` and `:original_requirement`. For example:
`|    +--- apache:commons-io:1.4 -> commons-io:commons-io:2.6`
``` ruby
{
original_name: "apache:commons-io",
original_requirement: "1.4",
name: "commons-io:commons-io",
requirement: "2.6",
type: "runtimeClassPath",  
}
```
NB Bibliothecary already uses the `:original_name` key for transforming Packagist/Drupal package names.

Capture original_{name,requirement} in maven parser, for gradle aliases.

---

lib/bibliothecary/parsers/npm.rb
spec/fixtures/npm-shrinkwrap.json
spec/parsers/npm_spec.rb

These files [have the same format](https://docs.npmjs.com/cli/v8/configuring-npm/package-lock-json#package-lockjson-vs-npm-shrinkwrapjson), so we can parse them the same way.

Handle shrinkwrap files the same as package-lock

---

lib/bibliothecary/parsers/nuget.rb
spec/fixtures/example.csproj
spec/fixtures/example.nuspec
spec/fixtures/packages.config
spec/parsers/nuget_spec.rb

This adds support for the `developmentDependency` attribute from `packages.config` files:
- https://docs.microsoft.com/en-us/nuget/reference/packages-config#examples
It also adds support `PackageReference`elements as used in `.csproj` files:
- https://docs.microsoft.com/en-us/nuget/consume-packages/package-references-in-project-files#controlling-dependency-assets
(Edit)
It also adds `developmentDependency` support for use in `.nuspec` files:
- https://docs.microsoft.com/en-us/nuget/reference/nuspec#developmentdependency

Update NuGet parser to handle dev dependencies

---

lib/bibliothecary/parsers/maven.rb
lib/bibliothecary/version.rb
spec/fixtures/gradle-dependencies-q.txt
spec/parsers/maven_spec.rb

Followup to https://github.com/librariesio/bibliothecary/pull/544 and https://github.com/librariesio/bibliothecary/pull/547
Sometimes a rename in `gradle-dependencies-q.txt` won't have a version requirement in the original manifest, so this adds support to recognize those cases as well.

Handle gradle renames that don't have a requirement in manifest.

---

lib/bibliothecary/parsers/maven.rb
lib/bibliothecary/version.rb
spec/fixtures/gradle-dependencies-q.txt
spec/parsers/maven_spec.rb

This adds support to parse projects in `gradle-dependencies-q.txt` as dependencies:
`|    +--- project :client (*)`
As well as aliases to projects:
`|    +--- my-group:my-alias-project-name:3.0.4 -> project :client (*)`
Although projects aren't the same as a regular library, they can be the parent of libraries in the dependency tree, so it's worth tracking them so you don't miss their child dependencies, with a group of `internal` and a requirement of `1.0.0`, e.g. `internal:client:1.0.0`

Gradle lockfile parser refactor to support aliases to projects

---

lib/bibliothecary/parsers/maven.rb
lib/bibliothecary/version.rb
spec/parsers/maven_spec.rb

It looks like `gradle dependencies` will sometimes output a project as a dependency **without a name**:
`+--- project :`
The most logical explanation is that the emptiness implies the current project's name, so we can interpolate that if we start tracking it.
Followup to https://github.com/librariesio/bibliothecary/pull/559

 Gradle lockfile parser: track "Project" names so we can interpolate them when needed later.

---

lib/bibliothecary/parsers/maven.rb
lib/bibliothecary/version.rb
spec/parsers/maven_spec.rb

This makes it safer to deal with these as deps, given maven's artifact name conventions (group:name:version).
e.g. `+--- project :api:my-internal-project` -> will now be interpreted as -> `internal:api-my-internal-project:1.0.0`
Leaves a minuscule chance for project name collisions, but the chances are slim.
Q: should we go with a different delimiter than `-`?

Replace colons in gradle project names with hyphens.

---

lib/bibliothecary/parsers/maven.rb
lib/bibliothecary/version.rb
spec/parsers/maven_spec.rb

* extract line-ending regexp so it's reusable elsewhere
* also, remove the "interpolate the project name" logic that was added in https://github.com/librariesio/bibliothecary/pull/560, because these are cycles [as confirmed by the gradle tests](https://github.com/gradle/gradle/blob/d1afb35abdbb2065de3086da885df8071b30049a/subprojects/diagnostics/src/integTest/groovy/org/gradle/api/tasks/diagnostics/DependencyInsightReportTaskIntegrationTest.groovy#L1697-L1753), so there's no reason to track them

Gradle lockfile parser: extract the line-ending regexp, and remove interpolation logic.

---

lib/bibliothecary/parsers/maven.rb
lib/bibliothecary/version.rb

@travatomic found a case where the sorting on gradle-dependencies-q.txt is non-deterministic on different platforms, which made us realize that the sorting done here is no longer necessary after https://github.com/librariesio/bibliothecary/pull/558  (in that PR, we expanded the uniqueness by adding original_name/original_requirement, which makes the sorting pointless)

Remove unnecessary sorting on gradle-dependencies-q.txt deps

---

lib/bibliothecary.rb
lib/bibliothecary/file_info.rb
lib/bibliothecary/runner.rb
lib/bibliothecary/runner/multi_manifest_filter.rb
lib/bibliothecary/version.rb
spec/bibliothecary_spec.rb

Followup to https://github.com/librariesio/bibliothecary/pull/564
We saw an error when an ASCII-8BIT yarn.lock file was run against bibliothecary after adding the "remove BOM" logic:
```
Encoding::CompatibilityError: incompatible encoding regexp match (UTF-8 regexp with ASCII-8BIT string)
```
We need to force the string's encoding to be utf8 before regex-ing it. ASCII-8BIT is fine to force, but if we need to support less common encodings like `utf-32be` in the future, we'll probably need to call `encode()` on the string too so it's properly encoded.

Handle non-utf8 files when removing BOM too, and DRY up into a helper method.

---

lib/bibliothecary/parsers/maven.rb
lib/bibliothecary/version.rb
spec/parsers/maven_spec.rb

In `Bibliothecary::Parsers::Maven.extract_pom_info` currently we allow you to lookup a pom element with a variable and we'll try to interpolate it, e.g.:
``` xml
<scm><url>${scm.url}</url></scm>
```
But you might also want to reference the element in the project namespace:
``` xml
<scm><url>${project.scm.url}</url></scm>
```
Or in the project's parent namespace:
``` xml
<scm><url>${project.parent.scm.url}</url></scm>
```
This adds support for the latter 2 lookups.
(interpolation was originally added in https://github.com/librariesio/bibliothecary/pull/456)

Maven.extract_pom_info: add support for more lookup variable namespaces.

---

lib/bibliothecary/parsers/pypi.rb
lib/bibliothecary/version.rb
spec/parsers/pypi_spec.rb

`pyproject.toml` can include poetry metadata, but it can also include project metadata according to [PEP 621](https://packaging.python.org/en/latest/specifications/declaring-project-metadata/), under the `[project]` field. This adds support for those `[project.dependencies]` deps.

pyproject.toml: support PEP621 projects too

---

lib/bibliothecary/cli.rb

Guessing this got renamed at some point and no one uses the included CLI to parse things.
To test:
./bibliothecary list somemanifest.file

Fix variable name for cli usage.

---

Gemfile
bibliothecary.gemspec
lib/bibliothecary/parsers/maven.rb
lib/bibliothecary/version.rb
spec/parsers/maven_spec.rb

* pegs us to an unpublished git sha of `strings-ansi` gem that supports stripping ansi color codes
* use the gem to sanitize input from `maven-dependency-tree.txt`

Strip ansi color codes from maven-dependency-tree.txt

---

lib/bibliothecary/parsers/nuget.rb
lib/bibliothecary/version.rb
spec/fixtures/packages.lock.json

Nuget projects can show up in Nuget lockfiles as dependencies, but they don't have versions and are not the same as packages, so bibliothecary can ignore them.

Nuget: ignore type="Project" deps in packages.lock.json

---

lib/bibliothecary/parsers/maven.rb
lib/bibliothecary/version.rb
spec/fixtures/pom-spaces-in-artifact-and-group.xml
spec/parsers/maven_spec.rb

* Strip whitespace inside `artifactId` and `groupId` tags in pom.xml files
* Be more aggressive with the lines we allow in `maven-resolved-dependencies.txt` to ensure only lines that match that format are returned as dependencies

fix: [sc-37248] Maven packages created with spaces in front

---

lib/bibliothecary/parsers/pypi.rb
lib/bibliothecary/version.rb
spec/fixtures/pyproject.toml
spec/parsers/pypi_spec.rb

Poetry 1.2.0 added support for dependency groups in https://github.com/python-poetry/poetry/pull/4260 , e.g.:
```
[tool.poetry.group.test.dependencies]
pytest = "^6.0.0"
pytest-mock = "*"
```
docs: https://github.com/python-poetry/poetry/blob/1.7.1/docs/managing-dependencies.md#dependency-groups

8.7.4: Add support for Poetry 1.2.0+'s dependency groups

---

lib/bibliothecary/multi_parsers/spdx.rb
lib/bibliothecary/parsers/maven.rb
lib/bibliothecary/parsers/pypi.rb

small style change: we should use `_REGEXP` as a suffix for constants instead of `_REGEX` so that the code is consistent and because Ruby's regular expression class is called `Regexp`.
(I considered keeping the old constants as deprecated constants and removing them in a later major version, but since we don't keep a CHANGELOG and we don't really do big major version releases, the result will be the same: downstream users will just be alerted that a constant they use is missing and they'll have to refer to the gem)

Standardize on _REGEXP names over _REGEX

---

lib/bibliothecary/parsers/go.rb
lib/bibliothecary/version.rb
spec/fixtures/go.mod
spec/parsers/go_spec.rb

this should fix the `replace` parsing bugs, where we currently get `{name: "foo -> bar", ...}` back for deps:
* adds parsing support for all go.mod directives: `require`, `replace`, `extract`, and `retract`
* uses `replace` results to replace any matching deps in `require` results
* ignore `exclude` results for now, since they're not related to `require` results

8.7.5: go.mod: adds official support for "replace" directive

---

lib/bibliothecary/parsers/go.rb

we discovered today that the `"replace"` directive only replaces the source code and doesn't actually replace the version reported (e.g. https://github.com/golang/go/issues/40513#issuecomment-667328207), so this adds a note about how bibliothecary results might differ from go's.

Add a note about how the go.mod parser deviates from go commands.

---

lib/bibliothecary/parsers/go.rb
lib/bibliothecary/version.rb
spec/fixtures/go-resolved-dependencies.json
spec/parsers/go_spec.rb

(followup to https://github.com/librariesio/bibliothecary/pull/585)
as we learned today, `"replace"` directives are not reported by things like `go mod graph`, and are only reported by `go list` if you ask for the ".Replace" directive, since `"replace"` only replaces the source code of the replaced version and not the actual version reported as used by go.
this adds support for the "Replace" field in `go-resolved-dependencies.json` files such that we can replace the deps during Bibliothecary analysis of those files, as we did in #585 with `go.mod` files.

8.7.6:  go-resolved-dependencies.json: adds official support for "replace" directive 

---

lib/bibliothecary/multi_parsers/cyclonedx.rb

Based off of the suggested filename patterns in the spec and from the SBOM everywhere openssf WG

Parse cyclonedx files named *.cdx.json or *.cdx.xml

---

lib/bibliothecary.rb
lib/bibliothecary/parsers/pypi.rb
lib/bibliothecary/version.rb
spec/bibliothecary_spec.rb

after forcing UTF-8 on all files before we read them in https://github.com/librariesio/bibliothecary/pull/565 , it was revealed that a pip-compile regexp we have is very generic and catching everything with `"require"` in the filename, which causes Bibliothecary.analyze() to blow up on binary files. 
This rescues the encoding error and skips analysis, although a better fix might be to detect binary files and skip reading them altogether (and to just fix that regexp so it's less generic).
closes https://github.com/librariesio/bibliothecary/issues/590

Bibliothecary.analyze(): skip analysis of binary files so we don't try to read invalid utf8

---

Gemfile
bibliothecary.gemspec
lib/bibliothecary/parsers/maven.rb
lib/bibliothecary/version.rb
spec/parsers/maven_spec.rb

bibliothecary uses `strings` and `strings-ansi` to strip ANSI escape codes from Maven lockfiles.
the gem [seems unmaintained](https://github.com/piotrmurach/strings-ansi/pull/2), so this removes the gem in favor of using its regex directly (and giving it credit).

Remove strings/strings-ansi gems in favor of copying their regexp.

---

CHANGELOG.md
lib/bibliothecary/parsers/maven.rb
lib/bibliothecary/version.rb
spec/parsers/maven_spec.rb

Refactoring of this was returning too early and not using any parent properties that are specified in the pom file.
property_value now returns nil for cases where it can't find the value and extract_property is properly using the fallback value in that case rather than requiring an interpolation of what it should have been

Fix using parent props for deps

---

CHANGELOG.md
lib/bibliothecary/parsers/maven.rb
lib/bibliothecary/version.rb
spec/fixtures/maven_parent_deps/jaxb-bom-2.3.1.pom.xml
spec/fixtures/maven_parent_deps/jaxb-runtime-2.3.1.pom.xml
spec/parsers/maven_spec.rb

Story details: https://app.shortcut.com/tidelift/story/46631
Add a new method which accepts an ordered array of pom xml strings ordered from child to parent. This allows Bibliothecary to parse more complex versioning scenarios such as a parent pom containing a versioned `dependency` element or a `dependencyManagement` element.

fix: [sc-46631] Libraries is returning wrong requirements for maven packages

---

lib/bibliothecary/parsers/cargo.rb
lib/bibliothecary/runner.rb
lib/bibliothecary/version.rb
spec/fixtures/go.mod
spec/parsers/go_spec.rb

The [new `go tool` command](https://tip.golang.org/doc/go1.24#tools) adds a new stanza to the bottom of `go.mod`, but we don't need it and it doesn't have version information. This PR just adds the stanza to our test fixture to ensure it gets parsed as a no-op.
If it's not from the stdlib, then the tool and its dependencies will get added as indirect deps to `go.mod` (it'd be nicer if it was `// tool` or something like that instead of `// indirect`).

12.1.1: add a regression spec for "go tool" deps to go.mod test fixture

---

CHANGELOG.md
lib/bibliothecary/parsers/npm.rb

The [Oj gem has a mimic_json() method](https://github.com/ohler55/oj/blob/develop/ext/oj/mimic_json.c#L785-L830) that overrides most of the JSON gem's methods. It's difficult to detect this because it's a C extension so `JSON.method(:parse).source_location` won't show you the location. It also means that ":allow_trailing_commas" wouldn't work with Oj:
```
> JSON.parse("[1,2,3,]", allow_trailing_comma: true)
(irb):1:in `load': expected array element, not an array close (after ) at line 1, column 22 [parse.c:618] (Oj::ParseError)
from (irb):1:in `<main>'
```
Luckily Oj did not override the JSON.parser() method, which returns an instance of the JSON parser. So use that directly to parse the JSON instead:
```
> JSON.parser.parse("[1,2,3,]", allow_trailing_comma: true)
=> [1, 2, 3]
```

NPM: add workaround for bun.lock's trailing commas, in case Oj.mimic_json was invoked.

---

CHANGELOG.md
lib/bibliothecary/parsers/npm.rb
lib/bibliothecary/version.rb

It's possible that a `pnpm-lock.yaml` may not have a `devDependencies` section, so fall back to `{}` in those cases instead of raising an error. For example:
```
lockfileVersion: '9.0'
importers:
.:
dependencies:
ansicolor:
specifier: ^2.0.3
version: 2.0.3
...
```

12.1.6: Don't raise an error if PNPM lockfile has no devDependencies section.

---

lib/bibliothecary/parsers/pypi.rb
spec/fixtures/poetry.lock
spec/parsers/pypi_spec.rb

(followup to https://github.com/librariesio/bibliothecary/pull/626)
It turns out some poetry.lock files -- maybe with older versions of Poetry? -- may contain deps without a category or group field.

12.1.9: bugfix from 12.1.8 in poetry.lock parser.

---

CHANGELOG.md
lib/bibliothecary/parsers/pypi.rb
lib/bibliothecary/version.rb
spec/fixtures/poetry.lock
spec/fixtures/pyproject.toml
spec/parsers/pypi_spec.rb

Poetry will take a package name from `pyproject.toml`, and store the [normalized name according to PyPa's rules](https://packaging.python.org/en/latest/specifications/name-normalization/#name-normalization) in `poetry.lock` without providing the original. This change normalizes all names for Poetry manifests so they're consistent, and stores the original in `Dependency#original_name` if it differs.

12.1.10: Pypi: normalize package names in Poetry manifests, and store the original too.

---

CHANGELOG.md
lib/bibliothecary/parsers/npm.rb
lib/bibliothecary/version.rb
spec/fixtures/pnpm-lockfile-version-5/package.json
spec/fixtures/pnpm-lockfile-version-5/pnpm-lock.yaml
spec/fixtures/pnpm-lockfile-version-6/package.json
spec/fixtures/pnpm-lockfile-version-6/pnpm-lock.yaml
spec/fixtures/pnpm-lockfile-version-9/package.json
spec/fixtures/pnpm-lockfile-version-9/pnpm-lock.yaml
spec/parsers/npm_spec.rb

Previously we weren't parsing deps like `@babel/types` correctly because of the ampersand, so this fix includes those deps correctly.

13.0.2: handle scoped dependencies in PNPM v5, v6, and v9 lockfiles.

---

CHANGELOG.md
lib/bibliothecary/analyser.rb
lib/bibliothecary/analyser/analysis.rb

The "Generic" type was added in https://github.com/librariesio/bibliothecary/pull/519 and then removed in https://github.com/librariesio/bibliothecary/pull/533.

Remove some leftovers from old "generic" parser code.

---

CHANGELOG.md
spec/fixtures/Pipfile
spec/fixtures/Pipfile.lock
spec/parsers/pypi_spec.rb

Looks like bibliothecary already considers Pipfile deps using "file" as `local: true`, so this just adds a regression test to ensure it going forward.

Add a regression test for pipfile file entries

---

CHANGELOG.md
lib/bibliothecary/parsers/pypi.rb
spec/fixtures/pylock.toml
spec/parsers/pypi_spec.rb

Introduced in [PEP 751](https://peps.python.org/pep-0751/) and documented [here](https://packaging.python.org/en/latest/specifications/pylock-toml/).
Note that "pylock.toml" isn't intended to give you a dependency tree. It defines a ["dependencies" table](https://packaging.python.org/en/latest/specifications/pylock-toml/#packages-dependencies) that is optional and undefined.
> [Recording the dependency graph for installation purposes](https://peps.python.org/pep-0751/#recording-the-dependency-graph-for-installation-purposes)
> A previous version of this PEP recorded the dependency graph of packages instead of a set of packages to install. The idea was that by recording the dependency graph you not only got more information, but it provided more flexibility by supporting more features …

Pypi: add "pylock.toml" lockfile parsing support
